apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-deployment
  labels:
    app: k8
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8
  template:
    metadata:
      labels:
        app: k8
    spec:
      containers:
      - name: k8
        image: 392520858220.dkr.ecr.us-east-2.amazonaws.com/k8:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: k8
spec:
  selector:
    app: k8
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80